# Generated by Django 5.2.1 on 2025-05-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_unique_isbn'),
        ('borrow_transaction', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_borrow_transaction', to='book.book'),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_borrow_transaction', to='user.user'),
        ),
    ]
