# Generated by Django 5.2.1 on 2025-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_transaction', '0002_alter_borrowtransaction_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], max_length=8),
        ),
    ]
