# Generated by Django 5.2.1 on 2025-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('isbn',), name='unique_isbn'),
        ),
    ]
